.TH YOUTUBE-DL "1" "December 2006" "youtube-dl" "User Commands"
.SH NAME
youtube-dl \- download a video file from YouTube.com
.SH DESCRIPTION
usage: youtube\-dl [options] video_url
.SS "options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
print this help text and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
print program version and exit
.TP
\fB\-u\fR USERNAME, \fB\-\-username\fR=\fIUSERNAME\fR
account username
.TP
\fB\-p\fR PASSWORD, \fB\-\-password\fR=\fIPASSWORD\fR
account password
.TP
\fB\-o\fR FILE, \fB\-\-output\fR=\fIFILE\fR
output video file name
.TP
\fB\-q\fR, \fB\-\-quiet\fR
activates quiet mode
.TP
\fB\-s\fR, \fB\-\-simulate\fR
do not download video
.TP
\fB\-t\fR, \fB\-\-title\fR
use title in file name
